services:
  db:
    image: mongo
    container_name: fma-db
    command: mongod --quiet --logpath /dev/null 
    ports:
      - "27017:27017"
    volumes:
      - "./db:/data/db"

  backend:
    container_name: fma-backend
    build:
      context: backend/
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
    volumes:
      - "./backend:/app"
    depends_on:
      - db

  frontend:
    container_name: fma-frontend
    build:
      context: frontend/
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"

volumes:
  db:

