FROM golang:1.23.4-alpine3.21 AS builder
WORKDIR /app

RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.2
RUN go install github.com/kisielk/errcheck@v1.8.0
COPY . ./

CMD ["go", "run", "."]
